nodes:
  - address: 3.230.76.212
    internal_address: 172.31.73.193
    user: ubuntu
    role: [controlplane, worker, etcd]
services:
  etcd:
    snapshot: true
    creation: 6h
    retention: 24h
ssh_key_path: ~/.ssh/jeff-rancher.key
# Required for external TLS termination with
# ingress-nginx v0.22+
ingress:
  provider: nginx
  options:
    use-forwarded-headers: "true"